---
title: "Composition d'un CV"
#author: ""
format: 
  html: 
    
    page-layout: article
    docx: default
    pdf: default
#  revealjs: 
#    chalkboard: true
#    smaller: true
#    scrollable: true
toc: true
reference-location: margin
citation-location: margin
#fig-cap-location: margin
editor: visual
---

[Un recruteur passe environ 30 secondes sur un CV](https://www.youtube.com/watch?v=XgNbAPyLb8U), surtout pour un poste très convoité. Il est évident que dans si peu de temps, il ne s'agit pas d'une lecture exhaustive, mais d'un premier tri. Comment passer cette étape de présélection et réussir à donner une première impression positive? Votre CV doit donner au recruteur des raisons pour le mettre dans le tas “à garder.”

Il va sans dire que la mise en page de votre CV doit être soignée, sobre, et que le résultat doit faire plaisir à lire, sans demander un effort particulier. Par exemple, si vous avez choisi de mettre les dates après vos diplômes dans la section “Formation,” faites de même dans la section “Expérience Professionnelle” et partout ailleurs où il y a des dates. Cette uniformité rend votre CV plus claire et guidera intuitivement le recruteur vers les informations que vous voulez mettre en valeur.

Évitez les polices de caractère extravagantes et l'utilisation excessive des mots en gras (bold). Votre CV, ainsi que votre lettre de motivation, doivent être écrits dans une police de caractère qui n'attire pas l'attention sur elle. Préférez une police de caractère serif, ou sans serif, communément employée. Dans vos documents professionnels, si vous ne maîtrisez pas les principes fondamentaux du design, ne mélangez pas plus que deux polices de caractère (par exemple: une police sans-serif pour les titres et une police serif pour le corps du texte).

Un CV doit bien cibler les besoins du poste pour lequel il a été rédigé, par exemple contenir les mots clés de l'annonce. En tant que candidat, vous devez mettre en évidence votre parcours et vos qualités mais aussi articuler votre projet professionnel. Si celui correspond à la description du poste votre CV aura la chance d'être retenu pour une relecture approfondie.

## Accroche

L'accroche est une partie du CV qui n'est pas obligatoire, mais qui peut être cruciale, car, en quelques mots bien choisis, elle facilite le recruteur à esquisser le portrait du candidat. Pensez à l'accroche comme au chapeau d'un article de journal.

“Le chapeau (souvent écrit chapô dans le milieu de la presse) est un texte généralement court, présenté en plus gros et/ou en caractères gras, précédant le corps d'un article de presse et dont le but est d'en encourager la lecture, par exemple en résumant le message.” (source: Wikipedia)

Dans le cas d'un CV, l'accroche se trouve au dessus du titre du CV et elle résume en quelques mots le projet professionnel du candidat tout en faisant le lien entre son profil et le poste en question.

Puisque chaque offre d'emploi est différente, l'accroche d'un CV doit être personnalisée en fonction de l'offre, reprendre par exemple les mots clés de l'offre.

Dans le cas d'un CV générique, l'accroche (3 à 6 lignes) explique qui vous êtes, ce qui vous anime dans la vie (vos valeurs personnelles) et quelle est la contribution que vous voulez faire dans la société.

## Les rubriques

Les rubriques d'un CV sont des groupements d'informations spécifiques qui guident la lecture d'un CV. Les informations listées dans ces rubriques sont souvent classées par ordre chronologique, ou par ordre d'importance/pertinence.

**Informations personnelles:** Sous cette rubrique vous mettez votre nom, et vos coordonnées. Vous n'êtes pas obligés de mettre de photo sur votre CV, mais si vous choisissez de le faire, évitez les photos personnelles recadrées, comme par exemple les photos de vacances. Si vous optez pour la photo, choisissez un portrait fait par un photographe professionnel, si possible.

**Formation/Éducation:** Sous cette rubrique vous mettez vos diplômes et certificats de formation. Suivez un ordre antéchronologique (du plus récent au plus ancien).

**Expérience professionnelle:** Cette rubrique est la plus difficile pour une personne qui débute dans le marché du travail, ou pour une personne qui veut changer de carrière. La raison est que les expériences professionnelles passées doivent en quelque sorte contribuer à l'esquisse d'un profil cohérent et en lien direct avec votre projet professionnel actuel: l'emploi pour lequel vous postulez, ou votre projet entrepreneurial.

**Langues:** Les langues étrangères sont une compétence à part entière. En plus, elles sont appréciées dans tous les secteurs et elles sont indispensables dans toutes les professions. Faites une rubrique spéciale sur votre CV pour les langues et n'oubliez pas de notez votre niveau. Dans le cadre européen CEFR (Common European Framework of Reference for Languages) il y a six niveaux:

A1: Débutant, A2: Élémentaire, B1: Intermédiaire, B2: Intermédiaire avancé, C1: Avancé, C2: Expert

**Compétences informatiques:** L'habilité informatique est de plus en plus explicitement demandée dans le marché du travail aujourd'hui. En tant que candidats vous n'êtes pas censés seulement maîtriser des logiciels bureautiques (suite Microsoft, Google, Libre Office, etc), mais aussi avoir des compétences sur une gamme d'application plus spécialisées comme les CMS (WordPress, Drupal, etc) les applications qui font de traitement de l'image, du son, et de la vidéo, et même des applications de gestion de projet (Slack, Teams, etc).

**Centres d'intérêt:** Sous cette rubrique vous pouvez mettre les activités extra-professionnelles: sportives, artistiques, associatives, etc. Attention, il s'agit d'activités pour lesquelles vous êtes passionné.e et que vous pratiquez régulièrement. Sinon, ce n'est pas la peine de les mentionner. Les activités de type "lecture, cinéma, jogging, visite de musée, etc" n'apportent rien d'extraordinaire sur votre profil et elles ne vous aident pas à vous faire démarquer.

## Activités

### Dans le rôle du recruteur (activité de groupe)

Vous dirigez l’entreprise française Multiprix implantée au Brésil et vous voulez changer l’apparence du site internet et le logo de la marque au Brésil.

Vous voulez donc recruter un.e web-designer.

Avec votre collègue:

1.  Lisez et analysez [les deux CV sélectionnés](https://canvas.its.virginia.edu/courses/104170/files/3384009?wrap=1). 
2.  [Présentez altérnativement la candidature que vous préfeérez. Pendant votre discussion appuyez vos arguments sur le parcours et le profil de chaque candidat.]{style="color: var(--ic-brand-font-color-dark); font-family: inherit; font-size: 1rem;"}

Pistes pour l’interaction :

-   Vous devez bien étudier chacun des deux CV avant la discussion, afin de connaître les forces et les faiblesses de chaque candidature. Vous pouvez même faire un tableau synthétique pour montrer les points forts et points faibles de chaque candidat. 
-   Il n’y a pas de CV nécessairement meilleur que l’autre.
-   L’objectif est que vous développez un argumentaire en illustrant votre propos à partir des éléments du CV. 

### Faire l'accroche

À partir des éléments du parcours professionnel de Cathia Lawson-Hall, imaginez et écrivez l'accroche de son CV. L'accroche doit être phrases) qui résume l'essentiel d'un profil professionnel.

Transcription:

> Je m’appelle Cathia Lawson-Hall, je suis banquière à la Société générale, je travaille dans la banque de financement et d’investissement et je m’occupe de l’Afrique. Je m’occupe des gros clients de la Société générale sur le continent africain.

> **Qui est Cathia Lawson-Hall ?**

> Je suis née au Togo, j’ai passé les premières années de ma vie au Togo avant de venir en France. Je vis en France depuis de nombreuses années. Et, aujourd’hui, je devrais plutôt dire que je vis entre la France et le continent africain dans son ensemble, parce que je voyage beaucoup et que je vais dans beaucoup de pays sur le continent. On dit souvent de moi que je suis quelqu’un d’énergique. Je suis volontaire, je suis énergique et j’ai un tempérament plutôt passionné.

> **Quel est votre parcours ?**

> J’ai fait un bac scientifique. Ensuite, je suis allée à Dauphine, où j’ai étudié de la finance et de l’économie. J’ai commencé comme analyste financier dans une société de bourse, avant de rejoindre la Société générale en décembre 1999, donc, toujours comme analyste financier. Ensuite, j’ai fait du conseil en financement, avant de devenir banquier-conseil en charge du continent africain. J’ai choisi cette filière financière parce que j’ai fait des études en finances. Je trouvais ça intéressant, a priori. Et, à mesure que j’avançais, je trouvais ça de plus en plus intéressant. Je me suis d’abord occupée de clients français avant de me diriger vers les clients africains, avec une volonté très forte d’offrir à mes clients africains le même service que j’offrais à mes clients français.
