---
title: "CV et LM --- Activités à faire en classe"
#author: ""
format: 
  html: 
    self-contained: true
    page-layout: article
    docx: default
    pdf: default
#  revealjs: 
#    chalkboard: true
#    smaller: true
#    scrollable: true
toc: true
reference-location: margin
citation-location: margin
#fig-cap-location: margin
editor: visual
---

## Accroche

À partir des éléments du parcours professionnel de Cathia Lawson-Hall, imaginez et écrivez l'accroche de son CV. L'accroche doit être court (1 – 2 phrases) qui résume l'essentiel d'un profil professionnel.

Transcription:

> Je m’appelle Cathia Lawson-Hall, je suis banquière à la Société générale, je travaille dans la banque de financement et d’investissement et je m’occupe de l’Afrique. Je m’occupe des gros clients de la Société générale sur le continent africain.

> **Qui est Cathia Lawson-Hall ?**

> Je suis née au Togo, j’ai passé les premières années de ma vie au Togo avant de venir en France. Je vis en France depuis de nombreuses années. Et, aujourd’hui, je devrais plutôt dire que je vis entre la France et le continent africain dans son ensemble, parce que je voyage beaucoup et que je vais dans beaucoup de pays sur le continent. On dit souvent de moi que je suis quelqu’un d’énergique. Je suis volontaire, je suis énergique et j’ai un tempérament plutôt passionné.

> **Quel est votre parcours ?**

> J’ai fait un bac scientifique. Ensuite, je suis allée à Dauphine, où j’ai étudié de la finance et de l’économie. J’ai commencé comme analyste financier dans une société de bourse, avant de rejoindre la Société générale en décembre 1999, donc, toujours comme analyste financier. Ensuite, j’ai fait du conseil en financement, avant de devenir banquier-conseil en charge du continent africain. J’ai choisi cette filière financière parce que j’ai fait des études en finances. Je trouvais ça intéressant, a priori. Et, à mesure que j’avançais, je trouvais ça de plus en plus intéressant. Je me suis d’abord occupée de clients français avant de me diriger vers les clients africains, avec une volonté très forte d’offrir à mes clients africains le même service que j’offrais à mes clients français.
