
## Profil créateur et dossier de candidature


Dans ce troisième module du cours, on se tourne du côté des ressources humaines (RH). 

Tout comme les entreprises, les individus qui sont actifs dans le monde professionnel doivent connaître leur valeurs et ce qui les rend compétitifs dans le marché du travail, au delà de leurs diplômes. 

Pour commencer à aborder cette question je vous propose de:  

1. Lire l'article "Les quatre métacompétences du futur" publié le 17/09/2020, par Gabrielle Halpern, Olivier Fronty sur Harvard Business Review France. [PDF vers l'article](https://canvas.its.virginia.edu/courses/264/files?preview=86329).
2. Répondre aux questions à propos de cette lecture sur Discussions.
         - Quel verbe est associé à la notion du métier? 
         - Comment est-ce que la notion du métier est perçue aujourd'hui? 
         - Quelle compétence est identifié comme centrale dans le socle des compétences du 21e siècle? 
         - Pourriez-vous résumer avec vos propres mots les quatre métacompétences proposées dans l'article?
         - Qu'est-ce que c'est un "CV augmenté?" 
         - Qu'est-ce qui différencie le CV augmenté d'un CV classique?
         - Ça vous intéresserait de créer un CV augmenté?   
4. Faites votre propre bilan de compétences sur [orientation-carriere.com](https://www.orientation-carriere.com/test.php). Le bilan est gratuit et les résultats s'affichent directement en ligne. Est-ce que les résultat s'alignent à vos attentes? Est-ce qu'il y a quelque chose que vous n'attendez pas et qui vous surprend? 
