### Entretien d’embauche

L’entretien d’embauche est la dernière étape d’une candidature réussie. Décrocher un entretien d’embauche signifie que votre candidature a passé toutes les étapes préliminaires de sélection et qu’elle s’est démarquée.

Vous êtes donc convoqué-e-s à un entretien d’embauche.

Un entretien d’embauche est une première rencontre personnelle avec votre éventuel futur employeur. Celui-ci a été impressionné par votre dossier (CV et lettre de motivation) et désire de vous connaître en tant que personne. Comme c’est souvent le cas (ça dépend, bien sûr, du secteur d’activité, ou du poste que vous convoitez), un entretien d’embauche n’est pas une vérification de vos compétences, mais une estimation de votre personnalité, de votre caractère.

Comme pour le CV et la lettre de motivation, tout compte dans un entretien d’embauche. Les choix de votre tenue vestimentaire, votre expression verbale, mais aussi tout ce qui relève de la communication non-verbale[[1]](<#_ftn1>).

Les entretiens d’embauche ne sont pas figés en un format. Ils se déroulent parfois à plusieurs (c’est le cas d’un candidat qui se trouve face à plusieurs personnes lors de son entretien) ou même en plusieurs étapes (le candidat rencontre d’abord son manager, puis dans un deuxième temps une personne de la direction du département des ressources humaines).

Chaque personne dans un entretien, ou chaque étape d’un entretien évalue différents aspects de la personnalité du / de la candidat-e, pour conclure à la fin, si celui-c / celle-ci est la personne idéale pour le poste.

### Questions à préparer

1. Pourriez-vous me parler un peu de vous? (Cette question ouvre souvent un entretien d’embauche. L’accroche de votre CV vous permettra d’aborder cette question.) [Regardez les conseils de cette vidéo](<https://www.youtube.com/watch?v=8i4BaK9tUws>) et [de celle-ci](<https://www.youtube.com/watch?v=sOEakEry_N8>).
2. Pourriez-vous me citer une de vos qualités et un de vos défauts?
3. Préférez-vous travailler seul(e) ou en équipe? 
4. Imaginez le scénario suivant: vous travaillez sur un projet en équipe et un de vos collègues semble avoir perdu sa motivation, que faites-vous?
5. Pourquoi vous et pas quelqu’un d’autre? Quel intérêt aurions nous à retenir votre candidature plutôt qu’une autre? [Regardez les conseils de cette vidéo: Pourquoi vous et pas quelqu’un d’autre?](<https://www.youtube.com/watch?v=TPBcU_3qWZI>)

<!-- -->



[[1]](<#_ftnref1>)La communication non-verbale part du principe que le corps envoie aussi des messages à un interlocuteur lors d’un échange. Ces messages sont très importants et peuvent dévoiler des intentions refoulées.</span>

