## Speed-networking

Quelques remarques préalables sur le speed-networking.

Comme son nom l’indique le speed-networking (en français “réseautage rapide”) est basé sur la pratique du speed-dating. Les séances de speed-dating consistent à des rencontres rapides entre célibataires en vue d’une liaison sentimentale. Ces rencontres ne durent pas plus que quelques minutes et fonctionnent sur la base de l’élimination. Dans un temps limité on rencontre un grand nombre de personnes pour ne garder le contact qu’avec celles avec qui il y a eu une étincelle (*spark*) et une envie mutuelle de se revoir. Si c’est le cas, des rendez-vous ultérieurs avec cette personne peuvent être organisés.

Le monde des affaires s’est aussi mis à cette pratique afin de permettre aux recruteurs de dénicher des talents et à tous les participants d’élargir leur réseau de connaissances professionnelles. Même si une rencontre de quelques minutes ne débouche pas immédiatement à la signature d’un contrat de travail, ou à un engagement de longue durée, les candidats, surtout des jeunes cadres[[1]](<#_ftn1>) au chômage, profitent aussi de ces séances. Une séance de speed-networking leur donne la possibilité d’articuler leur projet professionnel et de mettre en valeur des traits de leur caractère, deux éléments importants pour un candidats mais qui n’apparaissent pas sur un CV.



[[1]](<#_ftnref1>) Young executives

