## Séance de réseautage rapide

### Organisation de la séance

Déterminer la liste de questions avec les étudiants. Voir la liste préalable ci-dessous. Est-ce que vous voulez modifier, ajouter, ou soustraire des questions?

Une fois que les questions sont déterminées, on divise la classe en deux grand groupes. Pour 3 minutes chaque étudiant répond aux questions de ses partenaires de groupe. Au bout de 15 minutes les groupes se reforment et le jeu des questions recommence. À l’issue de cette séance, votre objectif est de parler à autant de personnes que possible afin de trouver le/la camarade qui ferait le meilleur camarade de groupe selon vos préférences. Notez son nom et donnez-le-moi à la fin du cours. Attention, ne lui dites pas! Il faut d’abord voir si les partenaires sont mutuellement d'accord avant de former les groupes. Je vais annoncer les groupes jeudi!

Questions:

1. D’habitude quels sont les trois adjectifs que tes amis/famille/proches utilisent le plus souvent pour décrire ta personnalité?
2. Qu’est-ce que tu aimes le plus quand tu travailles en groupe?
3. Qu’est-ce que tu aimes le moins quand tu travailles en groupe?
4. Quelle(s) qualité(s) cherches-tu à un partenaire de groupe? (une à trois qualités)
5. Comment est-ce que tu gardes le morale et ta motivation quand un travail est long et difficile?
6. Quelle aptitude (*ability*, *skill*, *talent*) aimerais-tu apprendre ou maîtriser?
7. Quelle de tes aptitudes seraient utile dans un travail de groupe?
8. Comment imagines-tu ta carrière professionnelle? Cadre (executive) dans une entreprise, ou créateur de ta propre entreprise?

<!-- -->



