## Comparaison CV

### Consigne de l'activité

Vous dirigez l’entreprise française Multiprix implantée au Brésil et vous voulez changer l’apparence du site internet et le logo de la marque au Brésil.

Vous voulez donc recruter un/e web-designer.

Avec votre collaborateur/collaboratrice:

1. Prenez 10 minutes à lire et à analyser les CV des deux meilleurs candidatures ci-joints. [Download this PDF: cv-comparaison.pdf](cv-comparaison.pdf)
2. Présentez altérnativement la candidature que vous préfèrez 6 minutes. Pendant votre discussion appuyez vos arguments sur le parcours et le profil de chaque candidat.




Pistes pour l’interaction :

- Vous devez bien étudier chacun des deux CV avant la discussion, afin de connaître les forces et les faiblesses de chaque candidature. Vous pouvez même un tableau synthétique pour montrer les points forts et points faibles de chaque candidat. 
- Il n’y a pas de CV nécessairement meilleur que l’autre.
- L’objectif est que vous développez un argumentaire en illustrant votre propos à partir des éléments du CV. 


