## Composition d'un CV

Un recruteur passe environ 30 secondes sur un CV, surtout pour un poste très convoité. Il est évident que dans si peu de temps, il ne s’agit pas d’une lecture exhaustive, mais d’un premier tri. Comment passer cette étape de présélection et réussir à donner une première impression positive? Votre CV doit donner au recruteur des raisons pour le mettre dans le tas “à garder.”</p><p>Il va sans dire que la mise en page de votre CV doit être soignée, sobre, et que le résultat doit faire plaisir à lire, sans demander un effort particulier. Par exemple, si vous avez choisi de mettre les dates après vos diplômes dans la section “Formation,” faites de même dans la section “Expérience Professionnelle” et partout ailleurs où il y a des dates. Cette uniformité rend votre CV plus claire et guidera intuitivement le recruteur vers les informations que vous voulez mettre en valeur.</p><p>Évitez les polices de caractère extravagantes et l’utilisation excessive des mots en gras (<em>bold</em>). Votre CV, ainsi que votre lettre de motivation, doivent être écrits dans une police de caractère qui n’attire pas l’attention sur elle. Préférez une police de caractère serif, ou sans serif, communément employées. Dans vos documents professionnels, ne mélangez pas plus que deux polices de caractère (par exemple: une pour les titres et une pour le corps du texte), si vous ne maîtrisez pas les principes fondamentaux du design.</p><p>Un CV doit bien cibler les besoins du poste pour lequel il a été rédigé, par exemple contenir les mots clés de l’annonce. En tant que candidat, vous devez mettre en évidence votre parcours et vos qualités mais aussi articuler votre projet professionnel. Si celui correspond à la description du poste votre CV aura la chance d’être retenu pour une relecture approfondie.</p></section>

L’accroche est une partie du CV qui n’est pas obligatoire, mais qui peut être cruciale, car, en quelques mots bien choisis, elle facilite le recruteur à esquisser le portrait du candidat. Pensez à l’accroche comme&nbsp;au chapeau d’un article de journal.</p><p>“Le chapeau (souvent écrit chapô dans le milieu de la presse) est un texte généralement court, présenté en plus gros et/ou en caractères gras, précédant le corps d’un article de presse et dont le but est d’en encourager la lecture, par exemple en résumant le message.” (source:<span></span><a href="https://fr.wikipedia.org/wiki/Chapeau_(presse_écrite)">Wikipedia</a>)</p><p>Dans le cas d’un CV, l’accroche se trouve au dessus du titre du CV et elle résume en quelques mots le projet professionnel du candidat tout en faisant le lien entre son profil et le poste en question.</p><p>Puisque chaque offre d’emploi est différente, l’accroche d’un CV doit être personnalisée en fonction de l’offre, reprendre par exemple les mots clés de l’offre.</p><p>Dans le cas d’un CV générique, comme celui que je vous demande de faire dans ce cours, pensez à l’accroche comme une phrase on un bref paragraph (3 à 6 lignes) qui explique qui vous êtes, ce qui vous anime dans la vie (vos valeurs personnelles) et quelle est la contribution que vous voulez faire dans la société.</p><p>Autrement dit, comment voulez-vous que les autres se rappellent de vous à la fin de votre vie? Pensez à cette question mais transposez-la dans l’avenir.</p></section>

### [Les rubriques](https://www.modeles-de-cv.com/) 
Trouvez ici des modèles des CV gratuits. 

*Informations personnelles:*
Sous cette rubrique vous mettez votre nom, et vos coordonnées. Vous n’êtes pas obligés de mettre de photo sur votre CV, mais si vous choisissez de le faire, évitez les photos personnelles recadrées, comme par exemple les photos de vacances. Si vous optez pour la photo, choisissez un portrait fait par un photographe professionnel, si possible.

- Formation: Sous cette rubrique vous mettez vos diplômes et certificats de formation. Suivez un ordre antéchronologique (du plus récent au plus ancien).
- Experience professionnelle: Cette rubrique est la plus difficile pour une personne qui débute dans le marché du travail, ou pour une personne qui veut changer de carrière. La raison est que les expériences professionnelles passées doivent en quelque sorte contribuer à l’esquisse d’un profil cohérent et en lien direct avec votre projet professionnel actuel: l’emploi pour lequel vous postulez, ou votre projet entrepreneurial.
- Langues: Les langues étrangères sont une compétence à part entière. En plus, elles sont appréciées dans tous les secteurs et elles sont indispensables dans toutes les professions. Faites une rubrique spéciale sur votre CV pour les langues et n’oubliez pas de notez votre niveau. Dans le cadre européen CEFR (Common European Framework of Reference for Languages) il y a six niveaux:

    - A1: Débutant
    - A2: Élémentaire
    - B1: Intermédiaire
    - B2: Intermédiaire avancé 
    - C1: Avancé
    - C2: Expert
- Compétences informatiques: L’habilité informatique est de plus en plus explicitement demandée dans le marché du travail aujourd’hui. En tant que candidats vous n’êtes pas censés seulement maîtriser des logiciels bureautiques (suite Microsoft, Google, Libre Office, etc), mais aussi avoir des compétences sur une gamme d’application plus spécialisées comme les CMS (WordPress, Drupal, etc) les applications qui font de traitement de l’image, du son, et de la vidéo, et même des applications de gestion de projet (Slack, Teams, etc).
- Centres d’intérêt: Sous cette rubrique vous pouvez mettre les activité extra-professionnelles: sportives, artistiques, associatives, etc. Attention, il s’agit d’activités pour lesquelles vous êtes passionné-e et que vous pratiquez régulièrement. Sinon, ce n’est pas la peine de les mentionner. Les activités de type "lecture, cinéma, jogging, visite de musée, etc," n’apportent rien d’extraordinaire sur votre profil et elles ne vous aident pas à vous faire démarquer. 

[Vidéo conseils d’un recruteur](https://www.youtube.com/watch?v=XgNbAPyLb8U)

