## Lettre de motivation

### Redaction de la lettre de motivation

Une lettre de motivation accompagne le CV et met en avant les qualifications, la formation, et les expériences d’un candidat.

La lettre de motivation peut être spontanée, ou rédigée pour répondre à une offre d’emploi.

C’est un document important parce qu’il permet en quelques lignes, d’esquisser le profil d’un-e candidat-e et les raisons pour lesquelles il/elle est intéressé-e par un projet professionnel.

Une lettre de motivation doit être claire, concise et aller droit à l’essentiel. Elle est composée d’habitude de trois paragraphes et elle ne doit pas excéder une page dactylographiée.

**Premier paragraphe “vous”:**

Dans ce paragraphe il faut montrer que vous connaissez l’entreprise à laquelle vous envoyez votre candidature. Il faut montrer au recruteur que vous avez fait vos recherches et que vous connaissez la taille, secteur, métiers, valeurs, mission, concurrents de l’entreprise à laquelle vous voulez travailler. Toutes ces informations sont facilement trouvées sur internet.

**Deuxième paragraphe “je”:**

Ce paragraphe concerne le candidat, son parcours (formation, expérience professionnelle) ainsi que tout autre talent ou compétence qui pourrait le distinguer aux yeux des recruteurs.

**Troisième paragraphe “nous”:**

Enfin, le troisième paragraphe concerne la collaboration entre le candidat et l’entreprise. Il imagine les contributions positives que le candidat apportera à l’entreprise.

Il va de soi que votre CV et lettre de motivation doivent être impeccables du point de vu grammatical. Un recruteur ne lira pas une lettre qui comporte des erreurs d’orthographe, des fautes d’accord, ou de conjugaison. Ces fautes ne sont pas forcément une indication du niveau d’expertise avec la langue (il arrive à tout le monde de faire des fautes de frappe *typos*), mais une marque de manque de rigueur, et peut-être d’un caractère mal-organisé, ou peu soigné. Votre dossier de candidature doit être lu, relu, et corrigé plusieurs fois par vous-même et une autre personne experte dans le domaine (camarade, prof, conseiller professionnel).

