---
title: "2.3 - Quiz de compréhension - 4 jeunes entreprises" 
---

Lisez et écoutez les interviews des fondateurs de 4 jeunes entreprises et puis répondez aux questions ci-dessous. Il y a 5 questions pour chaque interview. 

  

* [Matina Razafimahefa fondatrice de Sanya (interview imprimée).](https://afrique.latribune.fr/africa-tech/startups/2021-07-02/sayna-la-startup-malgache-qui-seduit-les-fonds-i-p-acceleration-technologies-et-miarakap-888179.html)Questions 1 – 5
* [Youssef Ouadahman co-fondateur de Meet my mama (interview imprimée)](https://www.journaldunet.com/ebusiness/commerce/1440841-youssef-oudahman-cofondateur-et-ceo-de-meetmymama/)  Questions 6 – 10 
* [Florian Gravier co-fondateur de Flaneurz (interview imprimée)](https://startup.info/fr/florian-gravier-flaneurz/) Questions 11 – 15 
* [Navbakhor Boudot, fondatrice de la marque Bahor (interview audio)](https://www.nouveaumodelepodcast.com/bahor)Questions 16 – 20

Questions: 

1. Quel le le secteur d'activité de Sayna?
2. Est-ce que le business model de Sayna a évolué depuis la création de l'entreprise jusqu'à aujourd'hui?
3. Comment expliquez-vous le terme "valider des compétences" ou "valider des acquis?"
4. Qui sont les clients de Sayna?
5. Quel a été l'impact de la pandémie pour Sayna?
6. Comment Youssef Oudahman explique-t-il la mission de son entreprise?
7. Quel rôle joue son expérience personnelle ainsi que celle des ses co-fondatrices quant à la conception de l'idée?
8. Quel est la spécificité des services de Meet My Mama?
9. Meet My Mama est une plateforme qui permet la mise en relation des différentes parties. Quelles sont les parties que la plateforme met en relation?
10. Quelle est la vision de l'entreprise pour l'avenir?
11. Quelle est le secteur d'activité de Flaneurz?
12. Comment l'histoire personnelle de Florian a influencé la conception de l'entreprise?
13. Est-ce que le marché du roller se porte bien? Pour quelles raisons?
14. Comment entendez-vous le terme "mobilité douce" ou "transport doux"?
15. Comment Flaneurz se démarque-t-elle de sa concurrence?
16.  Navbakhor Boudot a conçu et créer deux projets interconnectés. Quels sont-ils?
17.  Comment l'histoire personnelle de Navbakhor Boudot a influencé ses projets professionnelles en France?
18.  Quel est le secteur d'activité de Bahor?
19.  Qui travaille pour la marque Bahor et qui sont ses partenaires?
20.  Quelle est la spécificité de la marque Bahor?