---
title: "2.4 - Qu'en disent leurs fondateurs?" 
---

Aujourd'hui nous ferons deux activités:

- Activité de vocabulaire
- Ébauche de la déclaration de mission d'une entreprise

<!-- -->

## Mots du vocabulaire -- Activité de groupe

Utilisez l'onglet "Collaborations" et avec votre partenaire de groupe trouvez les définitions des mots du vocabulaire des affaires, donnés. Chaque groupe a 5 mots différents à définir.


<!-- -->

Voici une liste non exhaustive des ressources à consulter:

- [la page des définitions du site de l'Institut National de la Statistique et des Études Économiques (INSEE)](<https://www.insee.fr/fr/metadonnees/definitions>)<br>
- [le dico de l'éco](<https://www.economie.gouv.fr/facileco/dico-eco>)<br>
- [l'abécédaire de la BPI-France](<https://bpifrance-creation.fr/abecedaire>)<br>
- [le dictionnaire du site éducatif la finance pour tous](<https://www.lafinancepourtous.com/outils/dictionnaire/lettre/a/>)<br>
- [quelques mots essentiels en français-anglais](<https://englishlive.ef.com/fr-fr/blog/anglais-commercial/entreprise-en-anglais/>)
- [Bon usage de certains verbes qui posent problème](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/construction-et-emploi-des-verbes/>)

## Déclaration de mission -- Devoir pour [date]. 

Vous avez découvert 4 jeunes entreprises

- [Sayna](<https://sayna.io/>)
- [Meet my mama](<https://www.meetmymama.com/>)
- [Flaneurz](<https://www.flaneurz.com/fr/>)
- [Bahor](<https://bahor.fr/>)

<!-- -->

et ce que disent leurs fondateurs, à travers leurs interviews:

- [Matina Razafimahefa fondatrice de Sanya (interview écrite)](<https://afrique.latribune.fr/africa-tech/startups/2021-07-02/sayna-la-startup-malgache-qui-seduit-les-fonds-i-p-acceleration-technologies-et-miarakap-888179.html>)
- [Youssef Ouadahman co-fondateur de Meet my mama (interview écrite)](<https://www.journaldunet.com/ebusiness/commerce/1440841-youssef-oudahman-cofondateur-et-ceo-de-meetmymama/>)
- [Florian Gravier co-fondateur de Flaneurz (interview écrite)](<https://startup.info/fr/florian-gravier-flaneurz/>)
- [Navbakhor Boudot, fondatrice de la marque Bahor (interview audio)](<https://www.nouveaumodelepodcast.com/bahor>)

<!-- -->

Maintenant, imaginez que vous devez écrire la déclaration de mission d'une de ces entreprises. Faites l'ébauche (un paragraphe 100 -150 mots) d'une déclaration de mission chez vous pour jeudi 15 sept. Pour faire une déclaration de mission il faut répondre aux questions suivantes:

- "Que faisons-nous ?" - Clairement définir l'objectif principal de l'entreprise, ;
- "Comment le faisons-nous ?" - Parler de la façon dont l'objectif est atteint ;
- "Pour qui le faisons-nous ?" - Qui sont nos clients ;
- "Quelle valeur apportons-nous ?" - Quelle est la spécificité de notre produit ou service, qu'est-ce qui nous différencie de la compétition.

<!-- -->










