---
title: "2.6 - Activité de groupe -- phrases à corriger" 
---

1. Notre but primaire est de donner nos Mamas l’opportunité à réaliser leurs rêves **en leur donnant la valorisation professionnelle, économique, et sociale**. (Quel est le mot du vocabulaire qu'on a déjà vu mardi qui convient ici?)

2. Flaneurz propose **à chaque personne** de pouvoir rouler et marcher dans la même paire de chaussures, qui peuvent être spécifiquement conçues pour être uniques **à chaque personne**. (1. Répétition, 2. Est-ce que Flanneurz s'adresse à chaque personne?)

2. Chez Flaneurz, nous développons **des chaussures de tous les jours** avec une particularité; des rollers personnalisables. (Est-ce qu'on peut relier les *slades* à toutes les chaussures?)

3. Il est très important pour la nous ici a Meet My Mama de continuer a aider des femmes, parce que **ils** peuvent **rencontrer** aux **outres** femmes avec **problèmes similaires**, et **trouver force et courage entre elles même**. (Comment peut-on améliorer cette phrase en modifiant les parties en gras?)

4. Nos employées utilisent des tissus recyclés et écologiques des stocks dormants à Lyon à produire des vêtements élégants, uniques et éternels \*\*pour des travailleuses\*\*. (Quel est le problème avec la fin de cette phrase?)

5. L'objectif principal de Meet My Mama est pour «objectif d'aider à l'émancipation financière de femmes réfugiées ou issues de l'immigration en leur permettant de mettre à profit leurs compétences en cuisine», selon le fondateur lui-même. (Comment peut-on améliorer cette phrase?)

6. Nous voulons **créer la mobilité douce** par le roller qui **était** accessible pour **tout le monde**. (Comment faut-il changer les parties en gras pour améliorer cette phrase?)

7. La plupart des mères réfugiées ont une compétence particulière qui consiste à cuisiner leur nourriture traditionnelle, et le but de notre entreprise est de les aider et surtout celles qui ne parlent pas la langue en leur trouvant un emploi où elles pourront gagner de l'argent cuisiner des plats traditionnels. (Cette phrase est très longue, comment peut-on l'améliorer?)

8. En plus des repas délicieux faits maisons, les mamas parlent avec les clients et les connectent aux autres cultures par le décor. (Cette phrase est difficile à comprendre, comment peut-on l'améliorer?)

9. En créant ce roller détachable, nous avons rendu un produit qui est souvent **imposant**, à être pratique et chic. (Mot juste?)



