project: 
  type: book

toc: true
number-sections: false

book:
  title: "Business French" 
  # author: "Spyros"
  # date: "2/1/2023"
  page-navigation: true
  chapters:
    - index.qmd
    - syllabus.qmd
    - part: "Module 1"
      chapters:
        - mod1/1.1-intro.qmd
        - mod1/1.2.qmd
        - mod1/1.3.qmd
        - mod1/1.3.1.qmd
        - mod1/1.4.qmd
        - mod1/1.5.qmd
        - mod1/1.6.qmd
        - mod1/1.7.qmd
    
    - part: "Module 2"
      chapters:
      - mod2/2.1-objectifs.qmd
      - mod2/2.2.qmd
      - mod2/2.3.qmd
      - mod2/2.4.qmd
      - mod2/2.5.qmd
      - mod2/2.6.qmd      


    - part: "Module 3"
      chapters:
        - mod3/3.1.qmd
        - mod3/3.2.qmd 
        - mod3/3.3.qmd
        - mod3/3.4.qmd
        - mod3/3.5.qmd
        - mod3/3.6.qmd
        - mod3/3.7.qmd
        - mod3/3.8.qmd
        - mod3/3.9.qmd
        - mod3/3.10.qmd
        - mod3/3.11.qmd

    - part: "Module 4"
      chapters:
      - mod4/4.1.qmd
      - mod4/4.2.qmd
      - mod4/4.3.qmd
      - mod4/4.4.qmd
      - mod4/4.5.qmd
      - mod4/4.6.qmd
      - mod4/4.7.qmd
      - mod4/4.8.qmd
      - mod4/4.9.qmd
      - mod4/4.10.qmd
      - mod4/4.11.qmd

    - part: "Module 5"
      chapters:
      - mod5/5.1-intro.qmd
      - mod5/5.2.qmd
      - mod5/5.3.qmd
      - mod5/5.4.qmd
      - mod5/5.5.qmd
      - mod5/5.6.qmd
      - mod5/5.7.qmd
      - mod5/5.8.qmd
      - mod5/5.9.qmd
      - mod5/5.10.qmd
      - mod5/5.11.qmd
      - mod5/5.12.qmd

    - part: "Module 6"
      chapters:
      - mod6/6.1.qmd
      - mod6/6.2.qmd
      - mod6/6.3.qmd

# project:
#   type: website

# website:
#   title: "Business French"
#   navbar:
#     left:
#       - href: index.qmd 
#         text: Home
#       - href: syllabus.qmd
#         text: Syllabus
#       - modules.qmd
      

# format:
#   html:
#     theme: litera
#     css: styles.css
#     toc: true