---
title: "1.1 - Intro" 
format: 
  html: 
    page-layout: article
  docx: default
  pdf: default

toc: true
#reference-location: margin
citation-location: margin
fig-cap-location: margin
---

## Plan du cours: {.unnumbered}

- Étiquette de nom, extra longue (Activité pour briser la glace)^[footnote]

- Présentation du cours

- Devoirs

### Étiquette de nom, extra longue

La class est divisée en deux groupes: orange et bleu.

Chaque étudiant plie une feuille de papier pour créer une étiquette de table.

Sur un côté on écrit: 



- Nom 

- D'où viens-tu?

Sur l'autre côté, on répond à deux questions de la liste au choix. 



- Qu'est-ce que tu as fait cet été? Raconte une de tes aventures récentes! 

- Raconte une histoire drôle ou intéressante de ton enfance, ou de l'endroit où tu as grandi. 

- Qu'est-ce que tu voulais devenir quand tu étais enfant? 

- Quel est le talent pour lequel tu es connu dans ta famille?

Une fois que tout le monde a fini d'écrire, un étudiant du groupe orange rencontre un étudiant du group bleu. Ils font connaissance en partageant des informations et en se posant des question. Après cette rencontre initiale partagent ce qu'ils ont appris de l'étudiant qu'ils viennent de rencontrer.

[Méthode Agile](<https://myuva-my.sharepoint.com/personal/ss4ws_virginia_edu/Documents/zettlr/teaching/courses/fren-3035/agile.docx?web=1>)

### Devoirs 

- Partagez votre propre extra longue étiquette de nom dans la partie "Discussions" du site du cours. 

- Faites l'activité découverte d'une entreprise.

- Commencez votre lexique de vocabulaire du monde des affaires. Notez 5 mots nouveaux que vous avez appris avec leur définitions en Français.


