## Présentation informelle des idées d'entreprise

Aujourd’hui, les groupes présentent de façon informelle leur idée d’entreprise devant la classe. J’imagine que chaque idée est dans une phase de développement différente. Par conséquent, chaque groupe aura besoin des réactions différentes. N’hésitez donc pas de guider les retours (réactions et commentaires) de vos camarades sur ce dont vous avez besoin pour continuer le développement de vos idées.

L’objectif de cette présentation est de mettre à l’épreuve (tester) vos idées avec vos camarades et de recevoir des retours qui vous aideront d’améliorer vos projets. Comme vous êtes encore dans la phase initiale de vos projets, vous vous interrogez, sans doute, sur la validité de vos idées. N’hésitez donc pas de poser des questions à vos camarades sur ces doutes et les risques potentiels de vos idées, afin de les consolider ensemble et d’éviter que les incertitudes persistent dans leur développement ultérieur.

La semaine dernière, dans la phase du brainstorming, je vous ai donné<span></span>

[ce document](<https://canvas.its.virginia.edu/courses/264/files/326795?wrap=1>), basé sur le<span></span>

[Business Model Canvas](<https://canvas.its.virginia.edu/courses/264/pages/business-model-canvas?module_item_id=101265>). Dans votre présentation aujourd’hui, présentez ce que vous avez mis dans chaque case.

**Quel est le problème?**

Comme nous l’avons déjà vu avec toutes les entreprises étudiées, les idées des projets entrepreneuriaux naissent à partir des problèmes que les entrepreneurs ont observé dans leur quotidien. À ces problèmes, les entrepreneurs proposent des interventions alignées avec leurs valeurs personnelles et qui puissent avoir un impact social.

**Quelle est la solution? (Case 2 du modèle Canvas)**

Aux problèmes observés, les entrepreneurs proposent des solutions concrètes. Celles-ci sont ensuite développées en services ou produits et proposées à leurs clients.

**Qu’est-ce que votre idée change? (Case 2 du modèle Canvas)**

En quoi votre idée est différente des solutions déjà proposées dans le marché? Connaissez-vous votre concurrence?

**Qui elle concerne? (Case 1 du modèle Canvas)**

Qui sont les clients potentiels qui seraient intéressés par la solution proposée? Il est important d’identifier un segment du marché, afin de pouvoir cibler le marketing.

**Qu’est-ce qu’elle fait? (Cases 6 et 7 du modèle Canvas)**

Pour qu’une solution soit mise au marché, et qu’elle soit rentable, il faut imaginer les étapes de sa production. Quelles sont les ressources nécessaires pour sa production? Quels sont les métiers qui vont travailler pour la mettre au point? Quel est le secteur d’activité de l’entreprise?

<section id="déroulement-de-la-séance" class="level3"><h3>Déroulement de la séance&nbsp;</h3><p>Chaque groupe aura 5 minutes pour présenter son idée en commençant par le problème observé. À la fin de la présentation, il y aura 5 minutes de discussion et des retours.</p><p>Pour mieux profiter de la discussion, il serait pratique pour chaque groupe d’avoir identifié les points faibles, ou moins développés de son idée et guider la discussion vers ces points. Pour avoir les réponses qui vous aideront de continuer, posez à l’ensemble de la classe les questions qui vous préoccupent!</p></section>

