## Proposition d'une start-up

### L’objectif

Suite aux séances de brainstorming pour la recherche d’une idée d’entreprise et au partage informelle de votre idée en classe, vous êtes maintenant appelés à produire un document écrit qui présente les étapes essentielles de votre projet. Ce texte vous servira de base à des adaptations différentes selon le public que vous aurez à convaincre (investisseurs, partenaires commerciaux, clients, personnel, etc).

### La consigne
Produisez un texte de 800 mots, clair et convaincant sur votre projet en suivant les étapes suivantes. Ceci est un travail de groupe. 

Group 1:

Group 2: 

Group 3: 

Group 4: 

Group 5: 


### Étapes à suivre

**Quel est le problème?**

Comme nous l’avons déjà vu avec toutes les entreprises étudiées, les idées des projets entrepreneuriaux naissent à partir des problèmes que les entrepreneurs ont observé dans leur quotidien. À ces problèmes, les entrepreneurs proposent des interventions alignées avec leurs valeurs personnelles et qui puissent avoir un impact social. 

**Quelle est la solution? (Case 2 du modèle Canvas)**

Aux problèmes observés, les entrepreneurs proposent des solutions concrètes. Celles-ci sont ensuite développées en services ou produits et proposées à leurs clients. 

**Qu’est-ce que votre idée change?  (Case 2 du modèle Canvas)**

En quoi votre idée est différente des solutions déjà proposées dans le marché? Connaissez-vous votre concurrence? 

**Qui elle concerne? (Case 1 du modèle Canvas)**

Qui sont les clients potentiels qui seraient intéressés par la solution proposée? Il est important d’identifier un segment du marché, afin de pouvoir cibler le marketing.

**Qu’est-ce qu’elle fait? (Cases 6 et 7 du modèle Canvas)**

Pour qu’une solution soit mise au marché, et qu’elle soit rentable, il faut imaginer les étapes de sa production. Quelles sont les ressources nécessaires pour sa production? Quel est le secteur d’activité de l’entreprise? Quels types de métiers vous aurez besoin d’embaucher pour mettre votre idée au point?

### Boîte à outils

Ressources linguistiques pour vous aidez dans tous vos travaux en français

- Bon usage de certains verbes qui posent problème:
[Construction et emploi des verbes](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/construction-et-emploi-des-verbes/>)
- Bon usage de certaines prépositions qui posent problème:
[Prépositions et conjonctions](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/prepositions-et-conjonctions/>)
- [Organisateurs textuels et transitions logiques](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/organisateurs-textuels/>)
- [Marqueurs de cause](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/marqueurs-de-cause/>)
- [Marqueurs de conséquence](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/marqueurs-de-consequence/>)
- [Marqueurs de but et d’intention](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/marqueurs-de-but-et-dintention/>)
- [Marqueurs de condition et d’hypothèse](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/marqueurs-de-condition-et-dhypothese/>)
- [Marqueurs d’opposition et de restriction](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/marqueurs-de-concession-dopposition-et-de-restriction/>)
- [C’est vs il est](<https://ecampusontario.pressbooks.pub/consortiumclonetest/chapter/chapitre-10/#2.2>)