## Brainstorming

<section id="brainstorming" class="level2"><p>(source:<span></span><a href="https://fr.wikipedia.org/wiki/Brainstorming">Wikipédia</a>)</p><section id="quest-ce-que-le-brainstorming" class="level3"><h3>Qu’est-ce que le brainstorming?&nbsp;</h3><p>Le<span></span><em>brainstorming</em>, remue-méninges en Français est une activité de groupe. Tout seul-e on ne fait pas du remue-méninges, on réfléchit tout simplement.</p><p>C’est une méthode pour les groupes de générer le plus grand nombre d’idées possibles avant de se concentrer au développement de l’une d’entre elles plus tard.</p><p>Deux principes de base définissent le<span></span><em>brainstorming</em>&nbsp;: la suspension du jugement et la recherche la plus étendue possible.</p><p>Ces deux principes de base se traduisent par quatre règles:</p><ul><li>se laisser aller («&nbsp;freewheeling&nbsp;») pour obtenir le plus grand nombre d’idées possibles</li><li>toute idée, aussi farfelue (folle)<span></span>soit-elle, est la bienvenue</li><li>s’abstenir de toute critique des idées émises</li><li>rebondir («&nbsp;hitchhike&nbsp;») sur les idées exprimées: toute combinaison ou amélioration est la bienvenue.</li></ul><p>Ainsi, les suggestions absurdes et fantaisistes sont admises durant la phase de production et de stimulation mutuelles. En effet, les participants ayant une certaine réserve peuvent alors être incités à s’exprimer, par la dynamique de la formule et les interventions de l’animateur.</p><p>C’est pour amener à cet accouchement en toute quiétude que l’absence de critique, la suggestion d’idées sans aucun fondement réaliste, et le rythme, sont des éléments vitaux pour la réussite du processus.</p><section id="phase-1-préparer" class="level4"><h4>Phase 1: Préparer</h4><ul><li>Définition de l’objet du<span></span><em>brainstorming</em>: générer des idées pour une start-up. Quel est le problème? Qui sont les clients? Quelle est la solution?</li><li>Constitution de l’équipe de travail: 5 équipes de 2 partenaires</li><li>Organisation de la réunion: Pour commencer rappeler-vous de vos valeurs de groupe. Ensuite, pensez comment ces valeurs vont être servies quand vous essayez de trouver une solution à un problème?</li></ul></section><section id="phase-2-animer" class="level4"><h4>Phase 2: Animer</h4><ul><li>Ne jamais critiquer les idées des autres. Tout noter!</li><li>Débrider sa créativité en exprimant toutes ses idées sans réserve et sans autocensure.</li><li>Rebondir sur les idées des autres et les améliorer car la quantité d’idées est importante</li></ul></section><section id="phase-3-capitaliser-et-valoriser" class="level4"><h4>Phase 3: Capitaliser et valoriser</h4><p>Exploitation des idées recueillies: Reformuler, classer, hiérarchiser les idées sous une forme synthétique. Cette étape va vous permettre de décider si avec les idées recueillies vous avez un plan d’action, ou s’il faut recommencer le brainstorming à nouveau.</p></section></section></section>

<section class="footnotes footnotes-end-of-document" role="doc-endnotes"><p></p></section>

