## Le Pitch

À l'issue de la phase de la conceptualisation d'un projet, chaque équipe doit être en mesure d'expliquer son projet de façon claire et convaincante. C'est l'heure pitch! Dans le monde des affaires le pitch varie d'une brève présentation informelle, à un exposé formel devant des investisseurs, des partenaires, ou des clients. Le pitch est aussi important que l'idée même!

Le pitch peut avoir plusieurs fonctions selon le stade de l'évolution d'un projet. À un stade initial, il permet aux équipes de chercher des retours (feedback) pour améliorer leur idée, à un stade plus avancé, il permet aux équipes à chercher du financement (présenter leur idée à des investisseurs pour faire des levée de fonds), et même à des partenaires pour la promotion de l'entreprise.

Si le pitch n'arrive pas à convaincre son public, ou à susciter de l'intérêt, l'idée entrepreneuriale qui se trouve derrière, risque de tomber à l'eau (d'être abandonnée).

Le pitch est un discours bien organisé et bien répété(!) et qui prend des formes variées selon le public. La longueur de ces formes varie aussi. Le pitch peut aller d'une phrase-projet à un exposé beaucoup plus détaillé, comme celui de la vidéo ci-dessus.

