## Le pitch de la marque La Vie Laine

Regardons maintenant la vidéo de présentation du projet La Vie en Laine.

<iframe title="YouTube video player" src="https://www.youtube.com/embed/uqzdr4lWPyA" width="560" height="315" allowfullscreen="allowfullscreen" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" data-mce-fragment="1"></iframe>


La Vie Laine transcription de la vidéo: 

Présentation 

Bonjour à tous et merci pour votre présence. Nous sommes heureuses de vous présenter  aujourd’hui notre projet d’entreprise La Vie Laine. Le défi1 de cinq étudiantes bourguignonnes. Le but? Redynamiser la filière2 de laine des moutons française par la création d’une marque écoresponsable de prêt-à-porter 100% laine. Une démarche qui fait suite à l’arrivé massive des fibres synthétiques et à la délocalisation des industries3. Nos produits français regroupent des valeurs environnementales et sociétales. Notre entreprise produit et commercialise un vêtement de qualité ayant une traçabilité irréprochable et participe directement à l’économie des petites entreprises françaises. La Vie Laine offrira un nouveau souffle à la mode française. Ce n’est pas qu’une marque, c’est une proposition pour un nouveau mode de consommation. 

Éléments clés de la fabrication

Notre produit est en 100% laine, construit dans sa totalité en France dans le respect de l’environnement et suivant les tendances mode actuelles. À l’aide des éleveurs des moutons4 français, nous nous procurons la matière première en valorisant une laine brute composée de fibres 100% naturelles. Une matière noble et résistante que nos partenaires les entreprises de lavage, de filature5 et de tricotage6 de laine, transforment en un produit fin et doux puis en un produit fini, fidèle à nos valeurs et engagements. De plus, une société7 de transport nous permet un acheminement8 de chaque matériau entre chaque atelier. Enfin, chaque étape suit un protocole et un cahier des charges9 rigoureux10 ce qui fait de La Vie Laine un gage11 de transparence et de traçabilité12 des conditions d’élevage, du bien-être des moutons, jusqu’à la commercialisation de nos pulls. 

Proposition de valeur 

La Vie Laine mise sur un design de pulls à la intemporel et tendance pour séduire la gente féminine13. Celui-ci suivra les tendances et les saisons: chaud pour l’hiver et plus léger pour l’été. En plus, des collections été / hiver, notre marque proposera des collections capsules, afin de varier les plaisirs et toujours proposer de la nouveauté. Notre pull s’adresse à des femmes de tout âge soucieuses de l’environnement et de l’origine des produits, qui cherchent qualité et style. Par un circuit court et entièrement réalisé en France la réduction des émissions du CO2 et l’emploi d’industrie locale, consommer La Vie Laine, c’est faire un action écoresponsable et solidaire.  

Stratégie marketing 

Nous avons d’abord choisi de lancer notre produit dans une boutique en ligne pour pouvoir s’étendre et atteindre tout le territoire français. Puis nous ouvrirons notre propre boutique, à partir de la troisième année. Mais notre stratégie marketing ne s’arrête pas là. En effet, nous avons une valeur de zéro distance avec nos consommateurs. Grâce aux réseaux sociaux, tel qu’Instagram, nous allons pouvoir être au plus proche de nos clients et collaborateurs via des vidéos, des photos et des posts réguliers sur le fonctionnement et le cheminement  de nos produits, depuis les agriculteurs jusqu’à la conception et au modeling. Nous comptons aussi être présents dans les salons d’exposition de mode et d’agriculture, dans vos radios et dans de nombreux reportages.  

Nos impacts 

Vous l’aurez compris notre entreprise a la volonté de participer à la redynamisation d’une filière qui se meurt peu à peu. La filière de laine de mouton française. Ainsi, nous permettrons aux éleveurs des moutons français d’avoir un vrai débouché14 tous les ans, multipliant le prix de vente de leur laine par 6, ce qui permet de pouvoir couvrir le prix d’une prestation de tonte15. Nos entreprises partenaires, c’est-à-dire les agriculteurs et les ateliers sont déjà contactées. Nous n’avons plus qu’à nous lancer et vous présenter notre premier modèle. Alors n’hésitez pas à nous contacter via nos réseaux. Nous nous ferons un plaisir de répondre à vos questions.




## Activités
Avec votre partenaire, relisez le discours de l'équipe La Vie Laine et redistribuer chaque partie du discours dans une case du business model Canvas. 
Toujours avec votre partenaire, essayez de résumer le discours de présentation de La Vie Laine, en une phrase-projet comme celle d'OptiMiam:

"OptiMiam est une appli qui crée un "pont digital" entre les consommateurs et les commerçants du quartier, afin que les uns puissent avoir accès à des produits de qualité à un prix réduit, et que les autres vendent leurs produits périssables sans les gaspiller." 

 

défi: challenge↩︎

filière: Ensemble des activités productrices qui sont relatives, d’amont en aval, à un produit de base.↩︎

voir Module 1 La désindustrialisation à la française↩︎

éleveur: livestock farmer↩︎

filature: textile manufacturing↩︎

tricotage: knitting↩︎

société et synonyme d’entreprise↩︎

acheminement: transportation↩︎

cahier des charges: spécifications↩︎

rigoureux: strict↩︎

gage: garant↩︎

traçabilité: traceability↩︎

la gente féminine: les gens du genre féminin↩︎

débouché: outlet↩︎

tonte: shearing↩︎