## Comment trouver des idées d'entreprise? Les conseils des fondateurs de Onzic. 

Ce mardi on recevra encore une fois Christian Ingoumba pour 30 – 40 minutes. Pour cette deuxième et dernière visite, Christian nous parlera de la naissance de l’idée de son projet (Africans United Communities of Charlottesville), les différents stades de son développement, la recherche des partenaires, et, bien sûr, la presentation du projet (son pitch) pour des publics différents.

Après cette visite, vous retrouverez vos propres partenaires des groupes pour continuer votre travail sur la recherche de votre idée d’entreprise. Encore une fois, je vous encourage d’être audacieux-ses avec vos idées. Observez autour de vous et dans votre vie des problèmes qui pourraient se résoudre de façon plus créative. En guise d’inspiration, je vous invite à regarder cette vidéo où deux amis à court d’idées pour un projet d’entreprise demandent des conseils à Abou Touré et Dembo Dramé fondateurs de Onzic.

[L’origine du projet, la recherche de l’idée](<https://www.youtube.com/watch?v=TXL9T6kR3SM&list=PLKDXJtJALFV1Xb5y2SGNYgwvutaIjfI5C&index=2>)

Questions:

1. Dans le contexte de cette vidéo, qu'est-ce que ça veut dire "monter une boîte"? 
2. Qu’est-ce que Isham fait au début de la vidéo?
3. Dans un moment humoristique, on voit Isham se déguiser en Superman, en Jedi, en artiste et en Napoléon. Quelle est le message derrière ce segment de la vidéo?
4. Quelle est l’idée de l’appli Onzic? Résumez-la en une phrase projet.
5. Quelles ont été les étapes de développement d’Onzic?
6. Quelles sont les conseils des fondateurs d’Onzic pour les jeunes entrepreneurs qui cherchent des idées?
7. Dans quel secteur s'active la startup onzic? ([liste des secteurs sur Madyness](<https://www.maddyness.com/secteurs/>))
8. Avec les mots du vocabulaire ci-dessus décrivez le parcours de Onzic en donnant des exemples pour chaque étape. 



- conception et test d'un prototype 
    - le développement: l’industrialisation, l’expansion voire l’internationalisation 
    - gestation d'une idée
    - amorçage: première confrontation avec le marché (les retours des premiers clients permettent des ajustements de l’offre)