## Introduction

Vous avez monté votre boîte, vous avez créé un produit, ou un service attrayant vous l’avez testé auprès d’un circle restraint de consommateurs et maintenant vous voulez faire connaître à un circle plus grand du segment de votre clientèle que vos produits et services existent. Comment faire?

Il faut trouver une stratégie marketing (*mercatique*<span></span>

en français, mais le mot n’est pas couramment employé).

> Le marketing consiste à<span></span>
> 
> **l’ensemble des actions ayant pour objectifs d’étudier et d’influencer les besoins et comportements des consommateurs**<span></span>
> 
> et de réaliser en continu les adaptations de la production et de l’appareil commercial en fonction des besoins et comportements précédemment identifiés. ([source](<https://www.definitions-marketing.com/definition/marketing/>))

Les étapes du marketing:

1. Étude du marché. Cette étape permet de déterminer, parmi l’ensemble des consommateurs d’un marché, un segment spécifique qui serait susceptible d’être intéressé par le produit ou service de notre entreprise. Cette étape initiale permettra de mettre au point une stratégie de communication.
2. <span style="color: var(--ic-brand-font-color-dark); font-family: inherit; font-size: 1rem;">Stratégie de communication. Pour mettre au point une stratégie de communication, il faut savoir qui sont ses clients, par quel canal de communication les atteindre, comment construire le message de communication.</span>


<!-- -->

Toutes les entreprises ne communiquent pas de la même façon avec leurs clients. Par exemple, les entreprises bien établies n’ont pas besoin de se faire connaître au public. Au contraire, elles ont besoin de renouveler l’image de leur marque pour montrer à leurs clients qu’elles évoluent et qu’elles sont toujours à l’écoute de leurs besoins. Ces entreprises, donc, lorsqu’elles communiquent avec leurs clients, elles leur rappellent l’histoire de la marque, ses valeurs, et sa mission. Ces communications sont sporadiques.

Mais quand une entreprise lance un nouveau produit ou service il est nécessaire de communiquer cette offre avec ses clients. Pensez par exemple un constructeur automobile. Lorsqu’un nouveau modèle de la gamme est disponible des nouvelles publicités sont créées pour annoncer la nouvelle. Dans ce cas, pour que la communication soit réussie, la publicité met en valeur le plus grand atout du nouveau produit.

