---
title: "Le logo de votre entreprise"
---

<section id="création-du-logo" class="level2"><h2 class="anchored" data-anchor-id="création-du-logo">Création du logo<a class="anchorjs-link " href="http://localhost:4106/#cr%C3%A9ation-du-logo" aria-label="Anchor" data-anchorjs-icon=""></a></h2><p>Une fois que vous aurez le nom de votre marque et <span></span><a href="https://canvas.its.virginia.edu/courses/264/discussion_topics/68589" data-api-endpoint="https://canvas.its.virginia.edu/api/v1/courses/264/discussion_topics/68589" data-api-returntype="Discussion">votre slogan</a>, il vous faudra un logo! Pour la création de votre logo, je vous propose les options suivantes.</p><ul><li><p><a href="https://logo.com/">logo.com</a></p></li><li><p><a href="https://www.adobe.com/express/create/logo">Création de logo avec Adobe express</a></p></li><li><p><a href="https://www.canva.com/create/logos/">Création de logo avec Canva</a></p></li><li><p><a href="https://www.figma.com/community/plugin/768094929040207895/Logo-Creator">Création de logo avec Figma</a></p></li></ul><p>La plupart de ses sites (logo.com, Adobe Express, Canva) feront tout le gros travail de conception et d'exécution du logo pour vous. Il vous suffit de leur donner des informations comme le nom de votre marque, le slogan et le secteur d’activité de votre entreprise. À la fin du processus automatique, vous aurez la liberté de faire des modifications supplémentaires si vous le souhaiter. Une fois terminé vous téléchargerez votre logo et vous serez prêts à le déployer.</p><p>Figma est une application professionnelle qui nécessite un peu plus d’habilité avec les logiciels de design. Elle est, par contre,<span></span><a href="https://www.figma.com/education/"> gratuite pour les étudiants </a><span></span>et elle vous permet de collaborer dans le même fichier avec votre partenaire de groupe. Si ça vous tente d’essayer, je pourrai aussi vous aider à trouver vos repères.</p></section>

<section id="justification" class="level2"><h2 class="anchored" data-anchor-id="justification">Justification<a class="anchorjs-link " href="http://localhost:4106/#justification" aria-label="Anchor" data-anchorjs-icon=""></a></h2><p>Répétez le processus de création de logo trois fois pour arriver à des styles différents les uns des autres. Ces styles, si différents soient-ils, doivent tous refléter l’essence de votre marque, et correspondre aux attentes de votre segment de clientèle. Choisissez donc 3 styles et présentez-les sur ce fil de discussion en les accompagnant d’un paragraphe (250-300 mots minimum).</p><ul><li><p>Est-ce que chaque style que vous avez choisi peut représenter votre marque?</p></li><li><p>Comment chaque style représente tel ou tel aspect de l’identité de votre marque?</p></li><li><p>Pensez-vous que ces styles vont plaire à votre segment de clientèle? Pourquoi?</p></li><li><p>Est-ce qu’il y a des complémentarités intéressantes entre le nom de la marque, le slogan et les éléments graphiques? (Pensez aux<span></span><a href="https://canvas.its.virginia.edu/courses/264/discussion_topics/68584?module_item_id=174795"> affiches du stylo bic quatre couleurs </a><span></span>où le message: “Le stylo de toutes les matières scolaires” se construit comme un puzzle, à partir des morceaux disparates sur la page. Le message est en partie distribué aux éléments graphiques et en partie aux éléments textuels. Le travail de reconstruction du message est à la charge du public, qui, dans ce cas, ce sont les lycéens et les étudiants. Ceux-ci, se sont justement entraînés dans leurs cours à rechercher des indices et à suivre des pistes pour créer du sens.)</p></li></ul></section>

