## Le nom et le logo d’une marque

L’image et le mythe d’une marque reposent sur son nom et son logo. Ceux-ci fonctionnent comme point de repère pour le consommateur.

Il existe plusieurs types des noms pour une marque.

Les nom transparents: Bank of America, (le nom donne tout de suite une idée sur ce que l’activité de l’entreprise)
Noms du fondateur: Citroën, Ford, Disney… (cette approche est de moins en moins utilisée parce que les compagnies, surtout les startups, changent des propriétaires)
Noms communs: flaneurz, sayna, free (les mots “flâneur” (français) et “sayna” (malgache) existent dans le dictionnaire et ils se sont appropriés par les marques)
Noms composés: Optimiam, Wikipédia, Onedrive (se sont des mots valises)
Noms préfixés ou suffixés: iphone, shopify, Netflix (se sont des noms communs avec un préfixe ou un suffixe)
Les acronymes: IBM, BNP, AEG (Ce sont des noms à éviter parce qu’il est très difficile pour des startups d’associer leur valeurs avec un acronyme)
Des noms inventés: Häagen-Dazs (ça sonne danois mais en vérité ça ne veut rien dire)
Des noms-phrases: La vache qui rit (type de nom rare)
Quand vous êtes à la recherche d’un nom, mettez-vous à la place du consommateur mais regardez aussi la concurrence des acteurs qui sont déjà dans le marché. Un nom de marque doit être mémorable, lisible, prononçable.