## Brainstorming: générer une grande quantité des noms
Dans cette phase votre but est de générer le plus de noms possibles, sans vous censurer et sans jugement. Voici quelques idées pour vous aidez à commencer. Ne vous limitez pas à une seule langue mais faites attention au ton (engagé, ludique, technologique, sérieux…).

- Champ lexical: faites des listes des mots qui appartiennent dans le même champ lexical. Par exemple: “nature” dans le même champs lexical vous avez les mots arbre, la couleur verte, les mot animal, plante, fleur…

- Synonymes: faites des listes des synonymes

- Adjectif qualificatif + valeur(s) importante(s) pour votre entreprise

- Expressions autour d’un thème, une valeur, une fonctionnalité

- Jeux de mots

- Nom des personnages mythiques dont les attributs pourraient évoquer une valeur de la marque. Par exemple Hercule évoque la force.

- Néologismes: noms qui n’existent pas.

## Idées de noms 
Faire le tri pour garder les 5 noms les plus prometteurs

## Vérification 
Vérifiez les 5 noms de votre sélection avec les outils en ligne si le nom est disponible. Effectuez des recherches sur google, mais aussi sur l’Institut national de la propriété industrielle (INPI)

## Tester 
Avant d’arriver à votre sélection finale sollicitez l’avis de vos camarades.