## Typologie des slogans 

Dans votre recherche des slogans, vous avez, sans doute, remarqué trois grandes catégories.

1. **La phrase impérative ou injonctive:** le slogan impératif interpelle directement le public ciblé, c'est un appel à l'action. Le public est appelé à faire quelque chose qui aura une conséquence positive dans sa vie.

2. **La phrase nominale:** le slogan à la forme nominale (une phrase sans verbe) permet la création des messages courtes qui accélèrent l'accès au sens et qui visent à créer des associations positives dans l'esprit du consommateur.

3. **Assertions malines:** enfin, il y a une troisième catégorie des slogans où la phrase empreinte les caractéristiques d'un proverbe, d'un aphorisme, ou d'un jeu de mots. Dans ce cas, il y a souvent des allitérations (répétition des consonnes) ou des assonances (répétition des voyelles) avec le nom de la marque, voire de la répétition du nom de la marque dans le slogan. Ce type de slogan facilite la mémorisation de la marque ainsi qu'un bénéfice de cette marque pour le consommateur.

